version: '3'

services:
  gofly:
    restart: always
    build: .
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - DATABASE_NAME=go-fly
      - POSTGRES_PASSWORD=go-fly
      - PORT=8080
      - MASHAPE_KEY=${MASHAPE_KEY}
      - BASE_URL=${BASE_URL}
    depends_on:
      - postgres
    ports:
      - "8080:8080"
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=go-fly
      - POSTGRES_USER=postgres
      - POSTGRES_DB=go-fly
    volumes:
      - /opt/go-fly/postgresql:/var/lib/postgresql
    expose:
      - "5432"
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - ./certs:/opt/certs
    ports:
      - 80:80
      - 443:443